# coding: utf-8

"""
    Stable Diffusion

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.txt2_img_input import Txt2ImgInput  # noqa: E501
from swagger_client.rest import ApiException


class TestTxt2ImgInput(unittest.TestCase):
    """Txt2ImgInput unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTxt2ImgInput(self):
        """Test Txt2ImgInput"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.txt2_img_input.Txt2ImgInput()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
